import { DEMO_PIECES } from "./constants";
import PerformanceItem from "./components/PerformanceItem";

export default function App() {
  return (
    <div className="min-h-screen bg-white text-gray-900">
      <header className="border-b border-gray-100 px-6 py-20">
        <div className="mx-auto max-w-5xl text-center">
          <h1 className="mb-6 text-2xl font-bold tracking-tight md:text-4xl">
            Real-Time Hybrid Performance-MIDI-to-Score Transcription with
            Offline-to-Online Knowledge Distillation
          </h1>
          <div className="inline-flex items-center rounded border border-yellow-100 bg-yellow-50 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-yellow-700">
            Supplementary Demo Material
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-6 py-16">
        <section className="mb-16" aria-labelledby="gallery-title">
          <h2
            id="gallery-title"
            className="mb-4 text-xl font-bold uppercase tracking-[0.2em] text-gray-400"
          >
            Transcription Demo Gallery
          </h2>
          <div className="mb-8 h-px w-full bg-gray-100" />

          <div className="max-w-4xl">
            <p className="mb-8 text-base leading-relaxed text-gray-900">
              Four interactive examples demonstrate the live behavior and final
              transcription quality of our proposed hybrid system. Each example
              includes a live transcription demo video, the input MIDI, and the
              output score.
              <br />
              <br />
              We additionally compare the scores produced by our hybrid system
              with those generated by prior offline PM2S systems in the{" "}
              <strong>Transcribed Score Comparison</strong> tab.
            </p>

            <p className="mb-8 text-base leading-relaxed text-gray-900"></p>

            <aside className="mb-8 rounded-lg border border-amber-200 bg-amber-50/60 p-5 text-sm leading-relaxed text-amber-950">
              <strong>Out-of-distribution note.</strong> The examples below
              probe the <i>generalization</i> of our system, and are outside the
              distribution of classical music repertoire seen during training.
            </aside>
            <aside className="mb-8 rounded-lg border border-amber-200 bg-amber-50/60 p-5 text-sm leading-relaxed text-amber-950">
              <strong>Latency–quality note.</strong> To achieve lower structural
              delay in these demo, we uses substantially smaller context and
              overlap windows (L=160, S=80) than our proposed setting (L=512,
              S=256).
            </aside>

            {/* <p className="text-sm italic leading-relaxed text-gray-500">
              Use the three tabs in each example to compare the incoming
              performance with the live visualization and the final
              offline-refined notation.
            </p> */}
          </div>
        </section>

        <div className="space-y-6">
          {DEMO_PIECES.map((piece, index) => (
            <PerformanceItem key={piece.id} performance={piece} index={index} />
          ))}
        </div>
      </main>

      <footer className="border-t border-gray-100 px-6 py-16 text-center">
        <div className="mx-auto max-w-4xl font-mono text-[10px] uppercase tracking-widest text-gray-400">
          Real-Time Hybrid PM2S Transcription Demo
        </div>
      </footer>
    </div>
  );
}
